//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caPatchCEPCorreios
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOCALIDADE
    {
        public GLOCALIDADE()
        {
            this.GBAIRRO = new HashSet<GBAIRRO>();
            this.GLOGRADOURO = new HashSet<GLOGRADOURO>();
        }
    
        public int CODLOCALIDADE { get; set; }
        public string UF { get; set; }
        public string NOME { get; set; }
        public string CEP { get; set; }
        public string CODIFICACAO { get; set; }
        public string TIPOLOCALIDADE { get; set; }
        public Nullable<int> SUBORDINACAO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
    
        public virtual ICollection<GBAIRRO> GBAIRRO { get; set; }
        public virtual ICollection<GLOGRADOURO> GLOGRADOURO { get; set; }
    }
}
