//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caPatchCEPCorreios
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOGRADOURO
    {
        public int CODLOGRADOURO { get; set; }
        public string UF { get; set; }
        public Nullable<int> CODLOCALIDADE { get; set; }
        public Nullable<int> CODBAIRROINI { get; set; }
        public Nullable<int> CODBAIRROFIM { get; set; }
        public string NOME { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CEP { get; set; }
        public string TIPO { get; set; }
        public string UTILIZATIPO { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
    
        public virtual GBAIRRO GBAIRRO { get; set; }
        public virtual GBAIRRO GBAIRRO1 { get; set; }
        public virtual GLOCALIDADE GLOCALIDADE { get; set; }
    }
}
