//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace caPatchCEPCorreios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorporeRM_FabaoEntities : DbContext
    {
        public CorporeRM_FabaoEntities()
            : base("name=CorporeRM_FabaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GBAIRRO> GBAIRRO { get; set; }
        public DbSet<GLOCALIDADE> GLOCALIDADE { get; set; }
        public DbSet<GLOGRADOURO> GLOGRADOURO { get; set; }
    }
}
